### ISSUE TITLE
RecordMappers involving transformations on Maps do not compile

### ISSUE THREAD

**Issue by franbh** [nevillelyh/shapeless-datatype#13]
`Map`s which need to be mapped via an implicit conversion (e.g. `String => Array[Byte]`), or contain different case classes (even if they share the same structure: e.g. mapping from `Map[String, X]` to `Map[String, Y]` where `X(a: Int)` and `Y(a: Int)`), do not compile.

**Comment by nevillelyh** [comment]
Since `Map`s are not special cases and just treated as regular `value: T`, I think you'll have to define an implicit conversion between `Map[String, X] => Map[String, Y]` in this case?
