### ISSUE TITLE
Creating a generic AvroType

### ISSUE THREAD

**Issue by wzorgdrager** [nevillelyh/shapeless-datatype#18]
Is it possible to have a generic AvroType? So for instance like the following class:
```scala
class AvroDeserializationSchema[IN: ClassTag : TypeTag] {
   val t = AvroType[IN]
}
```
I'm struggling with this since I want to make a generic avro (de)serializer. 
Thanks in advance!

**Comment by nevillelyh** [comment]
What do you mean generic AvroType? IN should be a case class here and it already works on Avro generic records.

**Comment by wzorgdrager** [comment]
Yes, so if I have this class as stated above and try to do the following:
```scala
case class Person(name : String, age : Int)
val ser = new AvroDeserializationSchema[Person]()
```
However, in this situation I'm missing some implicits to properly compile.

To clarify my question: I would like to create a (de)serialization class which is able to transform GenericRecords into a case class. This (de)serialization class needs to be generic, otherwise I need to duplicate code for every different case class I have.

Thanks!

**Comment by nevillelyh** [comment]
This compiles for me. Can you be more specific what does not work?

```scala
import shapeless.datatype.avro.AvroType

import scala.reflect.ClassTag
import scala.reflect.runtime.universe._

object Test {
  def main(args: Array[String]): Unit = {
    val ser = new AvroDeserializationSchema[Person]()
  }
}

class AvroDeserializationSchema[IN: ClassTag : TypeTag] {
  val t = AvroType[IN]
}

case class Person(name : String, age : Int)
```

**Comment by nevillelyh** [comment]
Yeah if you are calling methods on `AvroType` that require those implicit through a method of your own, you'll have to transitively pass them in.

Out right now and will be back in a few weeks. Meanwhile look at the method signature in tests and feel free to try it yourself.

**Comment by wzorgdrager** [comment]
Yes I already did I was a bit confused about the 'L <: HList' generic (since I only have one generic), but I will further investigate that. Thanks for your help so far!

**Comment by nevillelyh** [comment]
More or less these arguments:
https://github.com/nevillelyh/shapeless-datatype/blob/master/avro/src/test/scala/shapeless/datatype/avro/AvroTypeSpec.scala#L28
