### ISSUE TITLE
[datastore]: StackOverflow for Case Class with over 22 fields

### ISSUE THREAD

**Issue by grahamar** [nevillelyh/shapeless-datatype#30]
I have a 4 converters where I'm calling `toEntityBuilder` and if I call `sbt clean compile` I consistently get the following StackOverflowError - https://gist.github.com/grahamar/f9100091d61f0313327a07e6aba06435#file-stack-txt

But If I don't `clean` it will work, which makes me think it's a race condition... All my code looks like - https://gist.github.com/grahamar/f9100091d61f0313327a07e6aba06435#file-authorconverter-scala, nothing complex.

My types are all very straight forward too:

```
case class Author(
  id: Long = 0L,
  source_id: Option[Long] = None,
  name: Option[String] = None,
  enabled: Option[Boolean] = None,
  avatar_url: Option[String] = None,
  extracted_name: Option[String] = None,
  item_name: Option[String] = None,
  unique_id: Option[String] = None,
  deleted_at: Option[String] = None,
  created_at: Option[String] = None,
  updated_at: Option[String] = None
)
```

Any help is appreciated, I don't have enough knowledge of shapeless to know where too look either...

**Comment by grahamar** [comment]
I think I found the issue, one of my case class types has 25 fields. When I reduce it to below 22, `clean compile` has no issues.

**Comment by nevillelyh** [comment]
Possibly a legit issue with shapeless & how I'm using it. cc @milessabin

**Comment by milessabin** [comment]
Interesting. It might be a shapeless issue, but I think that's unlikely.

25 is bigger than 22 though, so you might legitimately need more stack to compile ... have you tried increasing your stack size?

**Comment by nevillelyh** [comment]
I can't seem to reproduce it with a simple case class with 22+ fields. Do you have a complex type, like heavily nested case classes?

```
import shapeless.datatype.datastore._

object Test {
  def main(args: Array[String]): Unit = {
    val dt = DatastoreType[Record]
    dt.toEntity(Record())
  }
}

case class Record(
                  f1: Option[Long] = None,
                  f2: Option[Long] = None,
                  f3: Option[Long] = None,
                  f4: Option[Long] = None,
                  f5: Option[Long] = None,
                  f6: Option[Long] = None,
                  f7: Option[Long] = None,
                  f8: Option[Long] = None,
                  f9: Option[Long] = None,
                  f10: Option[Long] = None,
                  f11: Option[Long] = None,
                  f12: Option[Long] = None,
                  f13: Option[Long] = None,
                  f14: Option[Long] = None,
                  f15: Option[Long] = None,
                  f16: Option[Long] = None,
                  f17: Option[Long] = None,
                  f18: Option[Long] = None,
                  f19: Option[Long] = None,
                  f20: Option[Long] = None,
                  f21: Option[Long] = None,
                  f22: Option[Long] = None,
                  f23: Option[Long] = None,
                  f24: Option[Long] = None,
                  f25: Option[Long] = None,
                  f26: Option[Long] = None,
                  f27: Option[Long] = None,
                  f28: Option[Long] = None,
                  f29: Option[Long] = None,
                  f31: Option[Long] = None,
                  f32: Option[Long] = None,
                  f33: Option[Long] = None,
                  f34: Option[Long] = None,
                  f35: Option[Long] = None,
                  f36: Option[Long] = None,
                  f37: Option[Long] = None)
```

**Comment by grahamar** [comment]
I managed to reproduce it in a fresh simple app: https://github.com/grahamar/shapeless-issue

My type isn't heavily nested, but it could have something to do with the fact it's auto-generated...

`sbt clean compile` will give you the StackOverflow, and following that a `sbt compile` will work.

If it was my stack size, It shouldn't compile on the second try right...? My SBT JVM options during compilation:

```
export SBT_OPTS="-Xmx8G -Xms8G -Xss1M -XX:MaxMetaspaceSize=1G -XX:+CMSClassUnloadingEnabled -XX:ReservedCodeCacheSize=128m"
```

**Comment by milessabin** [comment]
@grahamar it could easily be right on the cusp. Try again with `-Xss2m` and report back.

**Comment by grahamar** [comment]
@milessabin you're right! Bumping did fix it. I just don't understand why the second "non-clean" compilation worked (without the extra stack size)...

Thanks for your help! 🤦‍♂

**Comment by milessabin** [comment]
> I just don't understand why the second "non-clean" compilation worked (before the extra stack size)...

The clean and non-clean builds follow slightly different paths ... one needs more stack than the other.

**Comment by grahamar** [comment]
Ah I didn't realise, thanks for that @milessabin
